### PR TITLE
cache pip dependencies

### PR DESCRIPTION
**Pull request by ericLemanissier**
depending on the os, pip install can take up to one minute. It is much quicker (few seconds) when using cache.
It requires pip packages to be defined in requirements.txt.
You will have to go to https://github.com/eirikb/conan-center-pr-status/settings/security_analysis to enable dependabot, so that the bot automatically makes pull requests.
eg

- https://github.com/ericLemanissier/proof-of-conan/pull/1
- https://github.com/ericLemanissier/proof-of-conan/pull/2
- https://github.com/ericLemanissier/proof-of-conan/pull/3

or
image

### CODE REVIEW

**Comment by eirikb** [comment]
Enabled to bot. It will make PRs for changes to requirements.txt - and I just have to click "okey dokay merge this"?

**Comment by ericLemanissier** [comment]
yep !

**Comment by ericLemanissier** [comment]
I looks like you had the same glich as I had on my fork. the npm version bump somehow failed. you have to go to https://github.com/eirikb/proof-of-conan/security/dependabot/1 and https://github.com/eirikb/proof-of-conan/security/dependabot/2 and click retry

**Comment by ericLemanissier** [comment]
mm, scratch my last comment. it worked:
https://github.com/eirikb/proof-of-conan/pull/18
https://github.com/eirikb/proof-of-conan/pull/19

**Pull request merged**
